TARGET = main

all: default
    
default: main

main: tentativaerro.c
	gcc -c tentativaerro.o -o tentativaerro

run: tentativaerro
	./tentativaerro

clean:
	-rm -f tentativaerro.o
	-rm -f tentativaerro
